language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dltswatts/docker-react-u -f Dockerfile.dev .

script:
  - docker run -e CI=true dltswatts/docker-react-u npm run test -- --coverage